<?php

namespace Domains\AutoBrands\Seeders;

use Domains\AutoBrands\Models\AutoBrand;
use Parents\Seeders\Seeder;

class AutoBrandsTableSeeder extends Seeder
{
    public function run(): void
    {
        $brands = [
            ["id" => "1", "name" => "AC"],
            ["id" => "5", "name" => "Acura"],
            ["id" => "7", "name" => "Alfa Romeo"],
            ["id" => "8", "name" => "Alpina"],
            ["id" => "12", "name" => "Asia"],
            ["id" => "14", "name" => "Aston Martin"],
            ["id" => "15", "name" => "Audi"],
            ["id" => "16", "name" => "Austin"],
            ["id" => "25", "name" => "Bentley"],
            ["id" => "30", "name" => "BMW"],
            ["id" => "36", "name" => "Bugatti"],
            ["id" => "37", "name" => "Buick"],
            ["id" => "40", "name" => "BYD"],
            ["id" => "41", "name" => "Cadillac"],
            ["id" => "45", "name" => "Caterham"],
            ["id" => "48", "name" => "Chery"],
            ["id" => "49", "name" => "Chevrolet"],
            ["id" => "50", "name" => "Chrysler"],
            ["id" => "52", "name" => "Citroen"],
            ["id" => "59", "name" => "Dacia"],
            ["id" => "60", "name" => "Dadi"],
            ["id" => "61", "name" => "Daewoo"],
            ["id" => "63", "name" => "Daihatsu"],
            ["id" => "64", "name" => "Daimler"],
            ["id" => "66", "name" => "Datsun"],
            ["id" => "68", "name" => "De Tomaso"],
            ["id" => "69", "name" => "Derways"],
            ["id" => "71", "name" => "Dodge"],
            ["id" => "72", "name" => "Doninvest"],
            ["id" => "74", "name" => "Eagle"],
            ["id" => "77", "name" => "FAW"],
            ["id" => "79", "name" => "Ferrari"],
            ["id" => "80", "name" => "Fiat"],
            ["id" => "82", "name" => "Ford"],
            ["id" => "88", "name" => "Geely"],
            ["id" => "89", "name" => "Geo"],
            ["id" => "90", "name" => "GMC"],
            ["id" => "95", "name" => "Great Wall"],
            ["id" => "104", "name" => "Honda"],
            ["id" => "107", "name" => "Hummer"],
            ["id" => "109", "name" => "Hyundai"],
            ["id" => "112", "name" => "Iran Khodro"],
            ["id" => "114", "name" => "Infiniti"],
            ["id" => "121", "name" => "Isuzu"],
            ["id" => "124", "name" => "JAC"],
            ["id" => "125", "name" => "Jaguar"],
            ["id" => "127", "name" => "Jeep"],
            ["id" => "134", "name" => "Kia"],
            ["id" => "137", "name" => "Koenigsegg"],
            ["id" => "145", "name" => "Lamborghini"],
            ["id" => "146", "name" => "Lancia"],
            ["id" => "147", "name" => "Land Rover"],
            ["id" => "148", "name" => "Landwind"],
            ["id" => "152", "name" => "Lexus"],
            ["id" => "153", "name" => "Lincoln"],
            ["id" => "154", "name" => "Lotus"],
            ["id" => "160", "name" => "Mahindra"],
            ["id" => "164", "name" => "Maserati"],
            ["id" => "165", "name" => "Maybach"],
            ["id" => "166", "name" => "Mazda"],
            ["id" => "167", "name" => "Mc Laren"],
            ["id" => "170", "name" => "Mercedes-Benz"],
            ["id" => "171", "name" => "Mercury"],
            ["id" => "173", "name" => "Metrocab"],
            ["id" => "174", "name" => "MG"],
            ["id" => "177", "name" => "Mini"],
            ["id" => "181", "name" => "Mitsubishi"],
            ["id" => "182", "name" => "Mitsuoka"],
            ["id" => "185", "name" => "Morgan"],
            ["id" => "191", "name" => "Nissan"],
            ["id" => "196", "name" => "Oldsmobile"],
            ["id" => "197", "name" => "Opel"],
            ["id" => "205", "name" => "Peugeot"],
            ["id" => "206", "name" => "Plymouth"],
            ["id" => "207", "name" => "Pontiac"],
            ["id" => "208", "name" => "Porsche"],
            ["id" => "211", "name" => "Proton"],
            ["id" => "212", "name" => "PUCH"],
            ["id" => "217", "name" => "Renault"],
            ["id" => "219", "name" => "Rolls-Royce"],
            ["id" => "221", "name" => "Rover"],
            ["id" => "222", "name" => "Saab"],
            ["id" => "225", "name" => "Renault Samsung"],
            ["id" => "226", "name" => "Saturn"],
            ["id" => "230", "name" => "Scion"],
            ["id" => "231", "name" => "SEAT"],
            ["id" => "232", "name" => "СеАЗ"],
            ["id" => "236", "name" => "Skoda"],
            ["id" => "237", "name" => "Smart"],
            ["id" => "242", "name" => "Spyker"],
            ["id" => "243", "name" => "Ssang Yong"],
            ["id" => "246", "name" => "Subaru"],
            ["id" => "247", "name" => "Suzuki"],
            ["id" => "250", "name" => "Talbot"],
            ["id" => "251", "name" => "TATA"],
            ["id" => "252", "name" => "Tatra"],
            ["id" => "254", "name" => "Tianma"],
            ["id" => "255", "name" => "Tianye"],
            ["id" => "260", "name" => "Toyota"],
            ["id" => "261", "name" => "Trabant"],
            ["id" => "273", "name" => "Volkswagen"],
            ["id" => "274", "name" => "Volvo"],
            ["id" => "276", "name" => "Wartburg"],
            ["id" => "280", "name" => "Wiesmann"],
            ["id" => "282", "name" => "Xin Kai"],
            ["id" => "284", "name" => "Zastava"],
            ["id" => "288", "name" => "ВАЗ"],
            ["id" => "292", "name" => "ГАЗ"],
            ["id" => "296", "name" => "ЗАЗ"],
            ["id" => "297", "name" => "ЗИЛ"],
            ["id" => "299", "name" => "ИЖ"],
            ["id" => "301", "name" => "КамАЗ"],
            ["id" => "311", "name" => "ЛуАЗ"],
            ["id" => "316", "name" => "Москвич"],
            ["id" => "336", "name" => "УАЗ"],
            ["id" => "490", "name" => "PGO"],
            ["id" => "534", "name" => "Vortex"],
            ["id" => "573", "name" => "Hafei"],
            ["id" => "588", "name" => "Foton"],
            ["id" => "597", "name" => "DongFeng"],
            ["id" => "645", "name" => "Lifan"],
            ["id" => "671", "name" => "Brilliance"],
            ["id" => "780", "name" => "ZX"],
            ["id" => "895", "name" => "СМЗ"],
            ["id" => "1038", "name" => "ТагАЗ"],
            ["id" => "1157", "name" => "JMC"],
            ["id" => "1284", "name" => "Changan"],
            ["id" => "1689", "name" => "Tesla"],
            ["id" => "2040", "name" => "Haima"],
            ["id" => "2347", "name" => "Santana"],
            ["id" => "2362", "name" => "Luxgen"],
            ["id" => "2372", "name" => "Fisker"],
            ["id" => "2390", "name" => "Бронто"],
            ["id" => "2394", "name" => "Brabus"],
            ["id" => "12373638", "name" => "Willys"],
            ["id" => "12383431", "name" => "Packard"],
        ];

        AutoBrand::insert($brands);
    }
}
